image:
  name: docker.innomius.com/servicepnr/node-builder:latest
  username: $DOCKER_USERNAME
  password: $DOCKER_PASSWORD

pipelines:
  branches:
    develop:
      - step:
          script:
            - npm install
            - npm run dev
            - mkdir target
            - cp -r index.html dist target/
            - cd target
            - tar -cvzf ../gw-component-tickets-status.tar.gz *
            - curl -v -u $NEXUS_WRITE_USER:$NEXUS_WRITE_PASS --upload-file ../gw-component-tickets-status.tar.gz https://repo.innomius.com/repository/innomius-raw/gw-component-tickets-status.tar.gz
            - aws s3 cp ../gw-component-tickets-status.tar.gz s3://innomius-binary-repo/
